#! /usr/bin/env bash

# Base16 color reference
# color00 # Base 00 - Black
# color01 # Base 08 - Red
# color02 # Base 0B - Green
# color03 # Base 0A - Yellow
# color04 # Base 0D - Blue
# color05 # Base 0E - Magenta
# color06 # Base 0C - Cyan
# color07 # Base 05 - White
# color08 # Base 03 - Bright Black
# color09 # Base 08 - Bright Red
# color10 # Base 0B - Bright Green
# color11 # Base 0A - Bright Yellow
# color12 # Base 0D - Bright Blue
# color13 # Base 0E - Bright Magenta
# color14 # Base 0C - Bright Cyan
# color15 # Base 07 - Bright White
# color16 # Base 09
# color17 # Base 0F
# color18 # Base 01
# color19 # Base 02
# color20 # Base 04
# color21 # Base 06
# color_foreground # Base 05
# color_background # Base 00

generate_tag()
{
  awk -F "\"" -v pattern="^$1" -v tagname="$2" '
  $0~pattern{gsub("/","",$2); printf "%s: '\''",tagname; printf "#%s",$2; printf "'\''"}
  ' $HOME/.base16_theme
}

{
  theme_name=$(sed -n -e 's/#[[:space:]]\(.*\)[[:space:]]scheme.*/\1/p' $HOME/.base16_theme)
  echo "// $theme_name theme generated by base16-gen.sh - $(date)"

  # color08 for light themes, color18 for dark themes
  echo "export const Theme = {
  main: '#1B222D',
  $((echo $theme_name | grep -Eiq light$) && generate_tag "color08" "minor" || generate_tag "color18" "minor"),
  accent: '#FFD484',
  red: '#E78482',
  green: '#8FC8BB',
  yellow: '#FFD484',
  orange: '#FFB374',
  blue: '#6DB3CE',
  magenta: '#AD82CB',
  cyan: '#7EDDDE',
  $(generate_tag "color_background" "background"),
  lightGrey: 'rgba(0, 0, 0, 0.05)',
  font: 'JetBrainsMono Nerd Font, monospace',
  lightShadow: '0 5px 10px rgba(0, 0, 0, 0.24)',
  mediumShadow: '0 8px 30px rgba(0, 0, 0, 0.24)',
  largeShadow: '0 30px 60px rgba(0, 0, 0, 0.24)',
  easing: 'cubic-bezier(0.4, 0, 0.2, 1)'
}" 
} > ThemeBase16.js

echo "Generated simple-bar theme for $theme_name"
