// OneDark theme generated by base16-gen.sh - Sun Jan  3 11:16:09 EST 2021
export const Theme = {
  main: '#1B222D',
  minor: '#353b45',
  accent: '#FFD484',
  red: '#E78482',
  green: '#8FC8BB',
  yellow: '#FFD484',
  orange: '#FFB374',
  blue: '#6DB3CE',
  magenta: '#AD82CB',
  cyan: '#7EDDDE',
  background: '#282c34',
  lightGrey: 'rgba(0, 0, 0, 0.05)',
  font: 'JetBrainsMono Nerd Font, monospace',
  lightShadow: '0 5px 10px rgba(0, 0, 0, 0.24)',
  mediumShadow: '0 8px 30px rgba(0, 0, 0, 0.24)',
  largeShadow: '0 30px 60px rgba(0, 0, 0, 0.24)',
  easing: 'cubic-bezier(0.4, 0, 0.2, 1)'
}
